[toolchain]
anchor_version = "1.2.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
learnfi_credentials = "BZLiJ62bzRryYp9mRobz47uA66WDgtfTXhhgM25tJyx5"

[programs.devnet]
learnfi_credentials = "BZLiJ62bzRryYp9mRobz47uA66WDgtfTXhhgM25tJyx5"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"
