import Link from "next/link";
import { connection } from "next/server";
import { ArrowDownRight, ArrowRight, BadgeCheck, BookOpen, Compass, GraduationCap, LockKeyhole, Play, Sparkles } from "lucide-react";
import { demoLessons } from "@/lib/demo-lessons";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { registerForLiveClass } from "./academy/[tutorial-slug]/actions";

const principles = [
  { icon: Compass, title: "Find your kind of teacher", text: "Explore how people teach, not just what they teach." },
  { icon: BookOpen, title: "Learn by doing", text: "Build a learning history from the work you actually complete." },
  { icon: BadgeCheck, title: "Carry what you earn", text: "Verifiable credentials connect your identity to real progress." },
];

export default async function Home() {
  await connection();
  const sessionClient = await createSupabaseServerClient();
  const { data: { user } } = await sessionClient.auth.getUser();
  let tutors: Array<{ user_id: string; headline: string | null; users: { username: string; display_name: string } | null }> = [];
  let lessons: Array<{ id: string; title: string; slug: string; summary: string | null; tutor_id: string; price_type: string; difficulty: string; duration_seconds: number | null; category_id: string | null }> = [];
  let categories: Array<{ id: string; name: string; slug: string }> = [];
  let liveClasses: any[] = [];
  const classRegistrationCounts = new Map<string, number>();
  try {
    const admin = createSupabaseAdminClient();
    const [{ data: profiles }, { data: published }, { data: categoryRows }] = await Promise.all([
      admin.from("tutor_profiles").select("user_id,headline,users!tutor_profiles_user_id_fkey(username,display_name)").eq("is_published", true).limit(4),
      admin.from("tutorials").select("id,title,slug,summary,tutor_id,price_type,difficulty,duration_seconds,category_id,status,video_processing_status").eq("status", "published").eq("video_processing_status", "ready").eq("is_published", true).order("published_at", { ascending: false }).limit(4),
      admin.from("tutorial_categories").select("id,name,slug").eq("is_active", true).order("sort_order"),
    ]);
    tutors = profiles ?? [];
    lessons = (published ?? []) as typeof lessons;
    categories = categoryRows ?? [];
    const { data: classRows } = await admin.from("live_classes").select("id,title,description,starts_at,duration_minutes,capacity,tutor_id").eq("status", "scheduled").gt("starts_at", new Date().toISOString()).order("starts_at").limit(3);
    const classIds = (classRows ?? []).map((item) => item.id);
    const classTutorIds = [...new Set((classRows ?? []).map((item) => item.tutor_id))];
    const [{ data: classUsers }, { data: registrations }] = await Promise.all([
      classTutorIds.length ? admin.from("users").select("id,username,display_name").in("id", classTutorIds) : Promise.resolve({ data: [] } as any),
      classIds.length ? admin.from("live_class_registrations").select("live_class_id").in("live_class_id", classIds).eq("status", "registered") : Promise.resolve({ data: [] } as any),
    ]);
    const userById = new Map((classUsers ?? []).map((item: { id: string; username: string; display_name: string }) => [item.id, item]));
    for (const registration of registrations ?? []) classRegistrationCounts.set(registration.live_class_id, (classRegistrationCounts.get(registration.live_class_id) ?? 0) + 1);
    liveClasses = (classRows ?? []).map((item) => ({ ...item, tutor: userById.get(item.tutor_id) }));
  } catch {
    tutors = [];
    lessons = [];
    categories = [];
    liveClasses = [];
  }
  const tutorNames = new Map(tutors.map((tutor) => [tutor.user_id, tutor.users?.display_name ?? "LearnFi tutor"]));

  return <main className="site-shell">
    <header className="topbar"><Link className="wordmark" href="/" aria-label="LearnFi home"><span className="brand-mark">L<span>f</span></span>learnfi</Link><nav className="main-nav" aria-label="Main navigation"><Link href="/academy">Academy</Link><Link href="/tutors">Tutors</Link><Link href="/learning-paths">Learning paths</Link><Link href="#classes">Upcoming classes</Link></nav><div className="landing-nav-actions"><Link className="landing-signin" href={user ? "/dashboard/learner" : "/auth/sign-in"}>{user ? "My learning" : "Sign in"}</Link><Link className="landing-signin" href="/auth/solana">Solana</Link><Link className="button button-primary sign-in" href="/tutor/onboard">Become a tutor</Link></div></header>
    <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="pulse-dot"/> A learning network for builders</div><h1>Your gateway to<br/><span className="serif-accent">onchain knowledge.</span></h1><p className="hero-description">LearnFi connects you with technical tutors who teach onchain skills in ways that fit how you learn.</p><div className="hero-actions"><Link className="button button-primary" href="/academy">Explore tutorials <ArrowRight size={17}/></Link><Link className="text-link" href="/tutor/onboard">Become a tutor <ArrowDownRight size={16}/></Link></div><div className="hero-footnote"><span className="footnote-line"/> Learn from people who know how to teach.</div></div>
      <div className="hero-visual" aria-label="A learning style matching illustration"><div className="visual-grid"/><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="match-panel"><div className="match-topline"><span>YOUR LEARNING FIT</span><span className="match-live"><i/> TEACHING STYLE</span></div><div className="match-profile"><div className="avatar avatar-you">Y</div><div><strong>Your learning style</strong><small>Project-based · visual · step-by-step</small></div><Sparkles size={17} className="sparkle"/></div><div className="match-divider"><span>MEETS</span></div><div className="match-profile tutor-preview"><div className="avatar avatar-tutor"><GraduationCap size={20}/></div><div><strong>A compatible tutor</strong><small>Learn with a style that fits you</small></div><ArrowRight size={17} className="match-arrow"/></div><div className="match-foot"><span className="match-foot-dot"/> Compatibility is based on styles you choose.</div></div><div className="floating-note"><span className="note-icon"><BookOpen size={15}/></span><span>Build real skills<small>Progress that belongs to you</small></span></div><span className="visual-caption">A better learning relationship starts here.</span></div>
    </section>
    <section className="trust-strip" id="how-it-works"><p>THE RIGHT PERSON CHANGES EVERYTHING</p><span className="strip-rule"/><p>DISCOVER <b>·</b> MATCH <b>·</b> LEARN <b>·</b> GROW</p></section>
    <section className="prototype-lessons" id="lesson-previews"><div className="prototype-heading"><div><div className="eyebrow muted-eyebrow">TUTORIAL PREVIEWS</div><h2>Explore a few ways to learn.</h2><p>Choose a topic and teaching style, then sign in to open the lesson.</p></div><Link className="button button-quiet" href="/academy">Explore the Academy <ArrowRight size={15}/></Link></div><div className="prototype-grid">{demoLessons.map((lesson) => { const next = `/tutorials/demo/${lesson.slug}`; const accessHref = user ? next : `/auth/sign-in?next=${encodeURIComponent(next)}`; return <article className="prototype-card" key={lesson.slug}><Link className={`prototype-poster poster-${lesson.visual}`} href={accessHref} aria-label={`${user ? "Open" : "Sign in to open"} ${lesson.title}`}><span className="poster-topic">{lesson.topic}</span><span className="poster-window"><span className="poster-window-top"><i/><i/><i/><span>{lesson.windowTitle}</span></span><span className="poster-code">{lesson.previewLines.map((line) => <span key={line}>{line}</span>)}</span><span className="poster-play"><Play size={19} fill="currentColor"/></span></span><span className="poster-lock"><LockKeyhole size={12}/> {user ? "OPEN LESSON" : "SIGN IN TO WATCH"}</span><span className="poster-duration">{lesson.duration}</span></Link><div className="prototype-card-body"><div className="prototype-style">{lesson.teachingStyle}</div><h3>{lesson.title}</h3><p className="prototype-excerpt">{lesson.excerpt}</p><Link className="prototype-card-link" href={accessHref}>{user ? "Open lesson" : "Sign in to watch"} <ArrowRight size={14}/></Link></div></article>; })}</div></section>
    <section className="landing-categories"><div className="eyebrow muted-eyebrow">EXPLORE BY CATEGORY</div><div className="landing-category-grid">{categories.map((category) => <Link key={category.id} href={`/academy?category=${encodeURIComponent(category.slug)}`}><span>{category.name}</span><ArrowRight size={14}/></Link>)}</div></section>
    <section className="landing-featured"><div className="network-heading"><div><div className="eyebrow muted-eyebrow">FEATURED TUTORIALS</div><h2>Start with something practical.</h2><p>Explore published lessons and see each tutor’s approach.</p></div><Link className="button button-quiet" href="/academy">Browse Academy <ArrowRight size={15}/></Link></div>{lessons.length ? <div className="landing-featured-grid">{lessons.map((lesson) => <Link href={`/academy/${lesson.slug}`} key={lesson.id}><span className="featured-topic">{categories.find((category) => category.id === lesson.category_id)?.name ?? "Technical tutorial"}</span><h3>{lesson.title}</h3><p>{lesson.summary ?? "Open this tutorial to see the learning details."}</p><div><span>{tutorNames.get(lesson.tutor_id) ?? "LearnFi tutor"}</span><span>{lesson.difficulty}</span><span>{lesson.duration_seconds ? `${Math.ceil(lesson.duration_seconds / 60)} min` : "Video"}</span><b>{lesson.price_type === "free" ? "FREE" : "PREMIUM"}</b></div></Link>)}</div> : <div className="landing-featured-empty">Published tutorials will appear here when tutors have video-ready lessons.</div>}</section>
    <section className="landing-network" id="tutors"><div className="network-heading"><div><div className="eyebrow muted-eyebrow">LEARN FROM PEOPLE</div><h2>Meet the teaching network.</h2><p>Explore tutor profiles and published tutorials.</p></div><Link className="button button-quiet" href="/tutors">Browse tutors <ArrowRight size={15}/></Link></div><div className="network-columns"><div className="network-tutor-list"><div className="network-list-label">PUBLISHED TUTOR PROFILES</div>{tutors.length ? tutors.map((tutor) => <Link className="network-tutor" href={`/tutors/${tutor.users?.username ?? ""}`} key={tutor.user_id}><span className="network-avatar">{(tutor.users?.display_name ?? "L").slice(0,1).toUpperCase()}</span><span className="network-tutor-copy"><strong>{tutor.users?.display_name ?? "LearnFi tutor"}</strong><small>{tutor.headline || "Teaching profile on LearnFi"}</small></span><ArrowRight size={15}/></Link>) : <div className="network-empty">Tutor profiles will appear here when tutors publish them.</div>}</div></div></section>
    <section className="principles" id="teaching"><div className="section-heading"><div><div className="eyebrow muted-eyebrow">A DIFFERENT WAY TO LEARN</div><h2>People first.<br/><span className="serif-accent">Progress that lasts.</span></h2></div><p>Find a tutor whose approach fits your goals, then build a learning history from work you complete.</p></div><div className="principle-list">{principles.map(({icon:Icon,title,text},index)=><article className="principle" key={title}><span className="principle-index">0{index+1}</span><span className="principle-icon"><Icon size={19} strokeWidth={1.7}/></span><div><h3>{title}</h3><p>{text}</p></div><ArrowRight size={17} className="principle-arrow"/></article>)}</div></section>
    <section className="landing-upcoming-classes" id="classes"><div className="network-heading"><div><div className="eyebrow muted-eyebrow">LIVE LEARNING</div><h2>Upcoming classes.</h2><p>Join a tutor-led technical session.</p></div><Link className="button button-quiet" href="/academy">View Academy <ArrowRight size={15}/></Link></div>{liveClasses.length ? <div className="landing-class-grid">{liveClasses.map((liveClass) => <article key={liveClass.id}><small>{new Date(liveClass.starts_at).toLocaleDateString(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" })}</small><h3>{liveClass.title}</h3><p>{liveClass.description}</p><div><span>With {liveClass.tutor?.display_name ?? "LearnFi tutor"}</span><span>{liveClass.duration_minutes} min{liveClass.capacity ? ` · ${classRegistrationCounts.get(liveClass.id) ?? 0}/${liveClass.capacity}` : ""}</span></div>{user ? <form action={registerForLiveClass}><input type="hidden" name="classId" value={liveClass.id}/><button className="button button-quiet" type="submit">Register <ArrowRight size={13}/></button></form> : <Link className="text-link" href="/auth/sign-in">Sign in to register <ArrowRight size={13}/></Link>}</article>)}</div> : <div className="landing-class-empty">Upcoming tutor-led classes will appear here when tutors schedule them.</div>}</section>
    <footer className="footer"><Link className="wordmark footer-brand" href="/"><span className="brand-mark">L<span>f</span></span>learnfi</Link><span>Build a learning history that goes with you.</span><Link className="footer-privacy" href="/privacy">Privacy policy</Link><span className="footer-status"><i/> BUILT FOR THE CURIOUS</span></footer>
  </main>;
}
