import Link from "next/link";
import { ArrowDownRight, ArrowRight, BadgeCheck, BookOpen, Compass, GraduationCap, Sparkles } from "lucide-react";

const principles = [
  { icon: Compass, title: "Find your kind of teacher", text: "Explore how people teach, not just what they teach." },
  { icon: BookOpen, title: "Learn by doing", text: "Build a learning history from the work you actually complete." },
  { icon: BadgeCheck, title: "Carry what you earn", text: "Verifiable credentials connect your identity to real progress." },
];

export default function Home() {
  return <main className="site-shell">
    <header className="topbar"><Link className="wordmark" href="/" aria-label="LearnFi home"><span className="brand-mark">L<span>f</span></span>learnfi</Link><nav className="main-nav" aria-label="Main navigation"><Link href="#how-it-works">How it works</Link><Link href="#teaching">Teaching styles</Link></nav><Link className="button button-quiet sign-in" href="/discover">Explore tutors <ArrowRight size={16}/></Link></header>
    <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="pulse-dot"/> A learning network for builders</div><h1>Find the person<br/>who makes it <span className="serif-accent">click.</span></h1><p className="hero-description">Learn from people who know how to teach. Find a tutor whose way of explaining fits the way you think.</p><div className="hero-actions"><Link className="button button-primary" href="/discover">Find your tutor <ArrowRight size={17}/></Link><Link className="text-link" href="#how-it-works">Get to know LearnFi <ArrowDownRight size={16}/></Link></div><div className="hero-footnote"><span className="footnote-line"/> No rankings to game. No traction to fake. Just better ways to learn.</div></div>
      <div className="hero-visual" aria-label="An illustrative preview of teaching-style matching"><div className="visual-grid"/><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="match-panel"><div className="match-topline"><span>YOUR LEARNING FIT</span><span className="match-live"><i/> MATCHING PREVIEW</span></div><div className="match-profile"><div className="avatar avatar-you">Y</div><div><strong>Your learning style</strong><small>Choose the styles that work for you</small></div><Sparkles size={17} className="sparkle"/></div><div className="match-divider"><span>MEETS</span></div><div className="match-profile tutor-preview"><div className="avatar avatar-tutor"><GraduationCap size={20}/></div><div><strong>A compatible tutor</strong><small>Teaching styles compared side by side</small></div><ArrowRight size={17} className="match-arrow"/></div><div className="match-foot"><span className="match-foot-dot"/> Compatibility is based on styles you choose.</div></div><div className="floating-note"><span className="note-icon"><BookOpen size={15}/></span><span>Learn at your own pace<small>Progress that belongs to you</small></span></div><span className="visual-caption">A better learning relationship starts here.</span></div>
    </section>
    <section className="trust-strip" id="how-it-works"><p>THE RIGHT PERSON CHANGES EVERYTHING</p><span className="strip-rule"/><p>DISCOVER <b>·</b> MATCH <b>·</b> LEARN <b>·</b> GROW</p></section>
    <section className="principles" id="teaching"><div className="section-heading"><div><div className="eyebrow muted-eyebrow">A different way to learn</div><h2>People first.<br/><span className="serif-accent">Progress that lasts.</span></h2></div><p>Courses give you content. LearnFi helps you find the person who can make it make sense.</p></div><div className="principle-list">{principles.map(({icon:Icon,title,text},index)=><article className="principle" key={title}><span className="principle-index">0{index+1}</span><span className="principle-icon"><Icon size={19} strokeWidth={1.7}/></span><div><h3>{title}</h3><p>{text}</p></div><ArrowRight size={17} className="principle-arrow"/></article>)}</div></section>
    <footer className="footer"><Link className="wordmark footer-brand" href="/"><span className="brand-mark">L<span>f</span></span>learnfi</Link><span>Build a learning history that goes with you.</span><span className="footer-status"><i/> BUILT FOR THE CURIOUS</span></footer>
  </main>;
}
