import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowRight, Check, ExternalLink, Plus, Save } from "lucide-react";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { createTutorial, publishTutorProfile, publishTutorial, saveTutorProfile } from "./actions";

const notices: Record<string, string> = { saved: "Tutor details saved. Review your profile before publishing it.", published: "Your tutor profile is now visible in discovery.", incomplete: "Add a headline, short bio, at least one teaching style, and one subject before publishing.", "tutorial-created": "Tutorial added as a draft.", "tutorial-published": "Tutorial published. Its free status is reserved by publication order.", "content-required": "Add an HTTPS content link before publishing a tutorial.", invalid: "Please check the fields and try again.", setup: "Save your tutor profile details first.", error: "We couldn’t save that change. Please try again." };

export default async function TutorDashboard({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const auth = await createSupabaseServerClient();
  const { data: { user } } = await auth.auth.getUser();
  if (!user) redirect("/auth/sign-in");
  const admin = createSupabaseAdminClient();
  const { data: account } = await admin.from("users").select("id,username,display_name").eq("auth_user_id", user.id).maybeSingle();
  if (!account) redirect("/auth/sign-in");
  const [{ data: profile }, { data: styles }, { data: subjects }, { data: selectedStyles }, { data: selectedSubjects }, { data: tutorials }, { status }] = await Promise.all([
    admin.from("tutor_profiles").select("headline,bio,technical_background,is_published").eq("user_id", account.id).maybeSingle(),
    admin.from("teaching_styles").select("id,name,description").order("name"),
    admin.from("subjects").select("id,name").order("name"),
    admin.from("tutor_teaching_styles").select("style_id").eq("tutor_id", account.id),
    admin.from("tutor_subjects").select("subject_id").eq("tutor_id", account.id),
    admin.from("tutorials").select("id,title,summary,content_url,position,is_published,tutorial_free_entitlements(slot)").eq("tutor_id", account.id).order("position"),
    searchParams,
  ]);
  const selectedStyleIds = new Set((selectedStyles ?? []).map((item) => item.style_id));
  const selectedSubjectIds = new Set((selectedSubjects ?? []).map((item) => item.subject_id));

  return <main className="discover-shell"><header className="topbar"><Link className="wordmark" href="/"><span className="brand-mark">L<span>f</span></span>learnfi</Link><div className="dashboard-nav"><Link href="/discover">Discover <ArrowRight size={15}/></Link><Link className="user-pill" href="/profile">@{account.username}</Link></div></header><section className="tutor-dashboard"><div className="eyebrow muted-eyebrow">TUTOR WORKSPACE</div><h1>Teach in your <span className="serif-accent">own way.</span></h1><p className="tutor-intro">Show learners what you teach, how you teach, and what they can learn with you.</p>{status && notices[status] && <p className={status === "published" || status === "tutorial-published" ? "tutor-notice success" : "tutor-notice"} role="status">{notices[status]}</p>}
    <div className="tutor-workspace-grid"><section className="tutor-workspace-panel"><div className="workspace-heading"><div><span className="step-label">01 · YOUR PROFILE</span><h2>What you teach and how.</h2></div>{profile?.is_published && <span className="published-label"><Check size={13}/> PUBLISHED</span>}</div><form action={saveTutorProfile} className="tutor-form"><label>PROFILE HEADLINE<input name="headline" maxLength={100} defaultValue={profile?.headline ?? ""} placeholder="e.g. Backend engineer teaching distributed systems" required/></label><label>ABOUT YOU<textarea name="bio" maxLength={3000} rows={4} defaultValue={profile?.bio ?? ""} placeholder="Tell learners about your technical work and what you enjoy teaching." required/></label><label>TECHNICAL BACKGROUND<textarea name="technicalBackground" maxLength={3000} rows={3} defaultValue={profile?.technical_background ?? ""} placeholder="Add relevant experience or context."/></label><fieldset><legend>HOW YOU TEACH</legend><div className="choice-grid">{(styles ?? []).map((style) => <label className="choice-item" key={style.id}><input type="checkbox" name="styleIds" value={style.id} defaultChecked={selectedStyleIds.has(style.id)}/><span><strong>{style.name}</strong><small>{style.description}</small></span></label>)}</div></fieldset><fieldset><legend>SUBJECTS YOU TEACH</legend><div className="choice-grid subject-choices">{(subjects ?? []).map((subject) => <label className="subject-choice" key={subject.id}><input type="checkbox" name="subjectIds" value={subject.id} defaultChecked={selectedSubjectIds.has(subject.id)}/><span>{subject.name}</span></label>)}</div></fieldset><button className="button button-primary" type="submit"><Save size={14}/> Save profile</button></form>{profile && <form action={publishTutorProfile} className="publish-profile-form"><button className="button button-quiet" type="submit">{profile.is_published ? "Republish profile" : "Publish tutor profile"}</button><small>Publishing makes your profile discoverable to learners.</small></form>}</section>
      <section className="tutor-workspace-panel"><div className="workspace-heading"><div><span className="step-label">02 · TUTORIALS</span><h2>Share something useful.</h2></div></div><form action={createTutorial} className="tutor-form create-tutorial-form"><label>TUTORIAL TITLE<input name="title" minLength={3} maxLength={140} placeholder="What will learners learn?" required/></label><label>SHORT DESCRIPTION<textarea name="summary" maxLength={500} rows={3} placeholder="Who is this for, and what will they be able to do?"/></label><label>LEARNING CONTENT LINK<input name="contentUrl" type="url" pattern="https://.*" placeholder="https://…"/><small>Use an HTTPS URL. You can publish after adding the content link.</small></label><label>SUBJECT<select name="subjectId" defaultValue=""><option value="">Choose a subject</option>{(subjects ?? []).map((subject) => <option value={subject.id} key={subject.id}>{subject.name}</option>)}</select></label><button className="button button-primary" type="submit"><Plus size={15}/> Add tutorial draft</button></form><div className="draft-tutorials">{tutorials?.length ? tutorials.map((tutorial) => <div className="draft-row" key={tutorial.id}><span className="tutorial-order">{String(tutorial.position).padStart(2,"0")}</span><div className="draft-title"><strong>{tutorial.title}</strong><small>{tutorial.is_published ? tutorial.tutorial_free_entitlements?.length ? "Published · Free" : "Published" : "Draft"}</small></div>{tutorial.is_published ? <Link href={`/tutorials/${tutorial.id}`} aria-label={`View ${tutorial.title}`}><ExternalLink size={14}/></Link> : <form action={publishTutorial}><input type="hidden" name="tutorialId" value={tutorial.id}/><button className="small-action" type="submit">Publish</button></form>}</div>) : <div className="tutorial-empty">Your tutorials will appear here after you add them. No activity is invented.</div>}</div></section></div></section></main>;
}
