"use client";

import { useState } from "react";
import { Plus, Save, Trash2 } from "lucide-react";
import { saveTutorialQuiz } from "./actions";

type QuizQuestion = { prompt: string; options: string[]; correctOption: number; explanation: string };

export function QuizEditor({ tutorialId, tutorialTitle }: { tutorialId: string; tutorialTitle: string }) {
  const [questions, setQuestions] = useState<QuizQuestion[]>([{ prompt: "", options: ["", ""], correctOption: 0, explanation: "" }]);
  const changeQuestion = (index: number, patch: Partial<QuizQuestion>) => setQuestions((current) => current.map((question, itemIndex) => itemIndex === index ? { ...question, ...patch } : question));
  const changeOption = (questionIndex: number, optionIndex: number, value: string) => setQuestions((current) => current.map((question, index) => index === questionIndex ? { ...question, options: question.options.map((option, itemIndex) => itemIndex === optionIndex ? value : option) } : question));
  return <details className="quiz-editor"><summary>Create or edit assessment</summary><form action={saveTutorialQuiz} className="tutor-form"><input type="hidden" name="tutorialId" value={tutorialId}/><input type="hidden" name="questionsJson" value={JSON.stringify(questions)}/><label>ASSESSMENT TITLE<input name="quizTitle" maxLength={160} defaultValue={`${tutorialTitle} assessment`} required/></label><label>PASSING SCORE (%)<input name="passingScore" type="number" min={1} max={100} defaultValue={70} required/></label>{questions.map((question, index) => <fieldset className="quiz-question-editor" key={index}><legend>QUESTION {index + 1}</legend><label>QUESTION TEXT<textarea value={question.prompt} onChange={(event) => changeQuestion(index, { prompt: event.target.value })} minLength={5} maxLength={1000} rows={2} required/></label>{question.options.map((option, optionIndex) => <div className="quiz-option-editor" key={optionIndex}><label><span>ANSWER {optionIndex + 1}</span><input value={option} onChange={(event) => changeOption(index, optionIndex, event.target.value)} maxLength={500} required/></label><label><input type="radio" name={`correct-${index}`} checked={question.correctOption === optionIndex} onChange={() => changeQuestion(index, { correctOption: optionIndex })}/> Correct</label></div>)}<div className="quiz-editor-actions">{question.options.length < 4 && <button type="button" onClick={() => changeQuestion(index, { options: [...question.options, ""] })}><Plus size={13}/> Add answer option</button>}{question.options.length > 2 && <button type="button" onClick={() => changeQuestion(index, { options: question.options.slice(0, -1), correctOption: Math.min(question.correctOption, question.options.length - 2) })}><Trash2 size={13}/> Remove last option</button>}</div><label>EXPLANATION (OPTIONAL)<textarea value={question.explanation} onChange={(event) => changeQuestion(index, { explanation: event.target.value })} maxLength={2000} rows={2}/></label></fieldset>)}<div className="quiz-editor-actions"><button type="button" disabled={questions.length >= 20} onClick={() => setQuestions((current) => [...current, { prompt: "", options: ["", ""], correctOption: 0, explanation: "" }])}><Plus size={13}/> Add question</button>{questions.length > 1 && <button type="button" onClick={() => setQuestions((current) => current.slice(0, -1))}><Trash2 size={13}/> Remove last question</button>}</div><button className="button button-quiet" type="submit"><Save size={13}/> Save assessment</button></form></details>;
}
